
import type { InventoryItem } from './types';

export const initialInventory: InventoryItem[] = [
  {
    id: '1',
    purchaseInvoiceNumber: 'INV-2023-001',
    vendorName: 'Global Auto Parts',
    purchaseDate: new Date('2023-10-15'),
    itemStdCode: 'AP-1023',
    itemCategory: 'Vehicle Part',
    productName: 'Brake Pad Set',
    productDetails: 'Front brake pads for Toyota Camry 2022',
    quantity: 50,
    storageLocation: 'Aisle 3, Shelf 2',
    unitPrice: 45.99,
    purchasePrice: 30.50,
    itemStatus: 'In Stock',
  },
  {
    id: '2',
    purchaseInvoiceNumber: 'INV-2023-002',
    vendorName: 'Machinery World',
    purchaseDate: new Date('2023-11-01'),
    itemStdCode: 'MW-5500',
    itemCategory: 'Machinery',
    productName: 'Hydraulic Press',
    productDetails: '10-ton hydraulic press for workshop use',
    quantity: 1,
    storageLocation: 'Workshop Area',
    unitPrice: 1200.0,
    purchasePrice: 950.0,
    itemStatus: 'In Stock',
  },
  {
    id: '3',
    purchaseInvoiceNumber: 'INV-2023-001',
    vendorName: 'Global Auto Parts',
    purchaseDate: new Date('2023-10-15'),
    itemStdCode: 'AC-8871',
    itemCategory: 'Accessories',
    productName: 'Phone Mount',
    productDetails: 'Universal car phone mount',
    quantity: 150,
    storageLocation: 'Aisle 1, Shelf 1',
    unitPrice: 12.5,
    purchasePrice: 7.0,
    itemStatus: 'In Stock',
    salesData: [
      { date: '2023-12-01', quantitySold: 20 },
      { date: '2024-01-10', quantitySold: 35 },
    ],
  },
  {
    id: '4',
    purchaseInvoiceNumber: 'INV-2023-003',
    vendorName: 'Solar Direct',
    purchaseDate: new Date('2023-11-20'),
    itemStdCode: 'SP-300W',
    itemCategory: 'Solar Material',
    productName: '300W Solar Panel',
    productDetails: 'Monocrystalline 300W solar panel',
    quantity: 20,
    storageLocation: 'Warehouse B, Rack 5',
    unitPrice: 150.0,
    purchasePrice: 110.0,
    itemStatus: 'In Stock',
  },
  {
    id: '5',
    purchaseInvoiceNumber: 'INV-2023-004',
    vendorName: 'Tool Supply Co.',
    purchaseDate: new Date('2023-12-05'),
    itemStdCode: 'TS-WRSET',
    itemCategory: 'Tools',
    productName: 'Wrench Set',
    productDetails: '24-piece metric and imperial wrench set',
    quantity: 5,
    storageLocation: 'Tool Cabinet 1',
    unitPrice: 75.0,
    purchasePrice: 50.0,
    itemStatus: 'Own use',
  },
  {
    id: '6',
    purchaseInvoiceNumber: 'INV-2023-001',
    vendorName: 'Global Auto Parts',
    purchaseDate: new Date('2023-10-15'),
    itemStdCode: 'AP-4501',
    itemCategory: 'Vehicle Part',
    productName: 'Alternator',
    productDetails: 'Alternator for Honda Civic 2020',
    quantity: 10,
    storageLocation: 'Aisle 5, Shelf 4',
    unitPrice: 180.0,
    purchasePrice: 135.0,
    itemStatus: 'In Stock',
    salesData: [{ date: '2024-02-15', quantitySold: 5 }],
  },
  {
    id: '7',
    purchaseInvoiceNumber: 'SALE-2024-002',
    vendorName: 'Battery Universe',
    purchaseDate: new Date('2024-01-20'),
    itemStdCode: 'BU-LFP100',
    itemCategory: 'Battery Part',
    productName: 'LiFePO4 Battery',
    productDetails: '12V 100Ah Lithium Iron Phosphate Battery',
    quantity: 0,
    storageLocation: 'Battery Rack 1',
    unitPrice: 299.99,
    purchasePrice: 220.0,
    itemStatus: 'Sold as vehicle',
    salesDate: new Date('2024-03-01'),
  },
  {
    id: '8',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110100013',
    itemCategory: 'Vehicle Part',
    productName: 'Upper link board (3-WHEELER)',
    productDetails: 'Upper link board (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '9',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110300018',
    itemCategory: 'Vehicle Part',
    productName: 'upper link board (jinniu COMMON)',
    productDetails: 'upper link board (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '10',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110300004',
    itemCategory: 'Vehicle Part',
    productName: 'Lower link board (3-WHEELER)',
    productDetails: 'Lower link board (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '11',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110300019',
    itemCategory: 'Vehicle Part',
    productName: 'Lower link board (3-WHEELER)',
    productDetails: 'Lower link board (3-WHEELER)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '12',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100105423',
    itemCategory: 'Vehicle Part',
    productName: 'Display (3-wheeler and jinniu COMMON)',
    productDetails: 'Display (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '13',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-100010554',
    itemCategory: 'Vehicle Part',
    productName: 'Motor (3-WHEELER)',
    productDetails: 'Motor (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '14',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JW-100400036',
    itemCategory: 'Vehicle Part',
    productName: 'Rear axle (3-WHEELER)',
    productDetails: 'Rear axle (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '15',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100440050',
    itemCategory: 'Vehicle Part',
    productName: 'Antitheft alarm (jinniu COMMON)',
    productDetails: 'Antitheft alarm (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '16',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100840045',
    itemCategory: 'Vehicle Part',
    productName: 'Antitheft alarm (3-WHEELER)',
    productDetails: 'Antitheft alarm (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '17',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110200110',
    itemCategory: 'Vehicle Part',
    productName: 'Front wheel (3-WHEELER)',
    productDetails: 'Front wheel (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '18',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-100200019',
    itemCategory: 'Vehicle Part',
    productName: 'Rear wheel (3-WHEELER)',
    productDetails: 'Rear wheel (3-WHEELER)',
    quantity: 8,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '19',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100203591',
    itemCategory: 'Vehicle Part',
    productName: 'Controller (jinniu LOW SPEED)',
    productDetails: 'Controller (jinniu LOW SPEED)',
    quantity: 75,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '20',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-100203592',
    itemCategory: 'Vehicle Part',
    productName: 'Controller (3-WHEELER)',
    productDetails: 'Controller (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '21',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120010001',
    itemCategory: 'Vehicle Part',
    productName: 'Tyre (jinniu COMMON)',
    productDetails: 'Tyre (jinniu COMMON)',
    quantity: 192,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '22',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-120010002',
    itemCategory: 'Vehicle Part',
    productName: 'Tyre (3-WHEELER)',
    productDetails: 'Tyre (3-WHEELER)',
    quantity: 8,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '23',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100010184',
    itemCategory: 'Vehicle Part',
    productName: 'Motor (jinniu LOW SPEED)',
    productDetails: 'Motor (jinniu LOW SPEED)',
    quantity: 75,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '24',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100010804',
    itemCategory: 'Vehicle Part',
    productName: 'Motor (jinniu HIGH SPEED)',
    productDetails: 'Motor (jinniu HIGH SPEED)',
    quantity: 21,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '25',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100200046',
    itemCategory: 'Vehicle Part',
    productName: 'Anti-rotating discs inside the motor (jinniu COMMON)',
    productDetails: 'Anti-rotating discs inside the motor (jinniu COMMON)',
    quantity: 188,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '26',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100203592',
    itemCategory: 'Vehicle Part',
    productName: 'Controller (jinniu HIGH SPEED)',
    productDetails: 'Controller (jinniu HIGH SPEED)',
    quantity: 21,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '27',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-101205993',
    itemCategory: 'Vehicle Part',
    productName: 'Front mud fender (jinniu COMMON)',
    productDetails: 'Front mud fender (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '28',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100130004',
    itemCategory: 'Vehicle Part',
    productName: 'Main cable (jinniu and jinniu COMMON)',
    productDetails: 'Main cable (jinniu and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '29',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100110779',
    itemCategory: 'Vehicle Part',
    productName: 'Main cable (jinniu LOW SPEED)',
    productDetails: 'Main cable (jinniu LOW SPEED)',
    quantity: 75,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '30',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110110780',
    itemCategory: 'Vehicle Part',
    productName: 'Main cable (3-WHEELER)',
    productDetails: 'Main cable (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '31',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100111009',
    itemCategory: 'Vehicle Part',
    productName: 'Main cable (jinniu HIGH SPEED)',
    productDetails: 'Main cable (jinniu HIGH SPEED)',
    quantity: 21,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '32',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100260009',
    itemCategory: 'Vehicle Part',
    productName: 'Speaker (3-wheeler and jinniu COMMON)',
    productDetails: 'Speaker (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '33',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100340065',
    itemCategory: 'Vehicle Part',
    productName: 'Left combination switch/grip (jinniu COMMON)',
    productDetails: 'Left combination switch/grip (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '34',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120430016',
    itemCategory: 'Vehicle Part',
    productName: 'Right combination switch/throttle (jinniu COMMON)',
    productDetails: 'Right combination switch/throttle (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '35',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110420400',
    itemCategory: 'Vehicle Part',
    productName: 'Brake disc brake (3-WHEELER)',
    productDetails: 'Brake disc brake (3-WHEELER)',
    quantity: 196,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '36',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-120040062',
    itemCategory: 'Vehicle Part',
    productName: 'Front disc brake (3-WHEELER)',
    productDetails: 'Front disc brake (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '37',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120420465',
    itemCategory: 'Vehicle Part',
    productName: 'Rear disc brake (3-WHEELER)',
    productDetails: 'Rear disc brake (3-WHEELER)',
    quantity: 8,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '38',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120150010',
    itemCategory: 'Vehicle Part',
    productName: 'CBS brake (jinniu COMMON)',
    productDetails: 'CBS brake (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '39',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120300007',
    itemCategory: 'Vehicle Part',
    productName: 'Rear mud fender (jinniu COMMON)',
    productDetails: 'Rear mud fender (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '40',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100200090',
    itemCategory: 'Vehicle Part',
    productName: 'MCB (jinniu LOW SPEED)',
    productDetails: 'MCB (jinniu LOW SPEED)',
    quantity: 75,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '41',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100090240',
    itemCategory: 'Vehicle Part',
    productName: 'Lock set (3-wheeler and jinniu COMMON)',
    productDetails: 'Lock set (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '42',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100420001',
    itemCategory: 'Vehicle Part',
    productName: 'Side sensor switch (jinniu COMMON)',
    productDetails: 'Side sensor switch (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '43',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-100240010',
    itemCategory: 'Vehicle Part',
    productName: 'Left combination switch/grip (3-WHEELER)',
    productDetails: 'Left combination switch/grip (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '44',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100150065',
    itemCategory: 'Vehicle Part',
    productName: 'Right combination switch/throttle (3-WHEELER)',
    productDetails: 'Right combination switch/throttle (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '45',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110180024',
    itemCategory: 'Vehicle Part',
    productName: 'Flasher (3-wheeler and jinniu COMMON)',
    productDetails: 'Flasher (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '46',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110170026',
    itemCategory: 'Vehicle Part',
    productName: 'Side stand spring (jinniu COMMON)',
    productDetails: 'Side stand spring (jinniu COMMON)',
    quantity: 192,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '47',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120240001',
    itemCategory: 'Vehicle Part',
    productName: 'Main stand spring (jinniu COMMON)',
    productDetails: 'Main stand spring (jinniu COMMON)',
    quantity: 192,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '48',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120120007',
    itemCategory: 'Vehicle Part',
    productName: 'Front and back mud skin clips (jinniu COMMON)',
    productDetails: 'Front and back mud skin clips (jinniu COMMON)',
    quantity: 192,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '49',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110120030',
    itemCategory: 'Vehicle Part',
    productName: 'Lock plate (3-WHEELER)',
    productDetails: 'Lock plate (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '50',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110120173',
    itemCategory: 'Vehicle Part',
    productName: 'Handle bar (3-WHEELER)',
    productDetails: 'Handle bar (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '51',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110110026',
    itemCategory: 'Vehicle Part',
    productName: 'Rear suspension (jinniu COMMON)',
    productDetails: 'Rear suspension (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '52',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100310002',
    itemCategory: 'Vehicle Part',
    productName: 'Front suspension (jinniu COMMON)',
    productDetails: 'Front suspension (jinniu COMMON)',
    quantity: 576,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '53',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-100190016',
    itemCategory: 'Vehicle Part',
    productName: 'Bearing (3-wheeler and jinniu COMMON)',
    productDetails: 'Bearing (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '54',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-100190014',
    itemCategory: 'Vehicle Part',
    productName: 'Left turn signal (3-WHEELER)',
    productDetails: 'Left turn signal (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '55',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-100190013',
    itemCategory: 'Vehicle Part',
    productName: 'Right turn signal (3-WHEELER)',
    productDetails: 'Right turn signal (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '56',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-150240001',
    itemCategory: 'Vehicle Part',
    productName: 'wire box (3-WHEELER)',
    productDetails: 'wire box (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '57',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-150250001',
    itemCategory: 'Vehicle Part',
    productName: 'wire box cover (3-WHEELER)',
    productDetails: 'wire box cover (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '58',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-150350002',
    itemCategory: 'Vehicle Part',
    productName: 'Handlebar (3-wheeler and jinniu COMMON)',
    productDetails: 'Handlebar (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '59',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-130030018',
    itemCategory: 'Vehicle Part',
    productName: 'Wind deflector (3-wheeler and jinniu COMMON)',
    productDetails: 'Wind deflector (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '60',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-150510002',
    itemCategory: 'Vehicle Part',
    productName: 'Left open pocket (3-wheeler and jinniu COMMON)',
    productDetails: 'Left open pocket (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '61',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-150510003',
    itemCategory: 'Vehicle Part',
    productName: 'Right open pocket (3-wheeler and jinniu COMMON)',
    productDetails: 'Right open pocket (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '62',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110018031',
    itemCategory: 'Vehicle Part',
    productName: 'Headlight (3-WHEELER)',
    productDetails: 'Headlight (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '63',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110080041',
    itemCategory: 'Vehicle Part',
    productName: 'Tail light (3-wheeler and jinniu COMMON)',
    productDetails: 'Tail light (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '64',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120250002',
    itemCategory: 'Vehicle Part',
    productName: 'Mud skin (3-wheeler and jinniu COMMON)',
    productDetails: 'Mud skin (3-wheeler and jinniu COMMON)',
    quantity: 204,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '65',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-150080001',
    itemCategory: 'Vehicle Part',
    productName: 'Trim on the left footrest (jinniu COMMON)',
    productDetails: 'Trim on the left footrest (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '66',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-150070001',
    itemCategory: 'Vehicle Part',
    productName: 'Trim on the right footrest (jinniu COMMON)',
    productDetails: 'Trim on the right footrest (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '67',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-150310001',
    itemCategory: 'Vehicle Part',
    productName: 'Left pedal lower trim (jinniu COMMON)',
    productDetails: 'Left pedal lower trim (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '68',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-150320001',
    itemCategory: 'Vehicle Part',
    productName: 'Right pedal lower trim (jinniu COMMON)',
    productDetails: 'Right pedal lower trim (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '69',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120360017',
    itemCategory: 'Vehicle Part',
    productName: 'Rear reflector (jinniu COMMON)',
    productDetails: 'Rear reflector (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '70',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120080018',
    itemCategory: 'Vehicle Part',
    productName: 'Side reflector (jinniu COMMON)',
    productDetails: 'Side reflector (jinniu COMMON)',
    quantity: 384,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '71',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120080032',
    itemCategory: 'Vehicle Part',
    productName: 'Lock wire (3-wheeler and jinniu COMMON)',
    productDetails: 'Lock wire (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '72',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-150570006',
    itemCategory: 'Vehicle Part',
    productName: 'Rear wheel trim (3-WHEELER)',
    productDetails: 'Rear wheel trim (3-WHEELER)',
    quantity: 8,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '73',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-200120001',
    itemCategory: 'Vehicle Part',
    productName: 'Plastic bag (3-wheeler and jinniu COMMON)',
    productDetails: 'Plastic bag (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '74',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-200230019',
    itemCategory: 'Vehicle Part',
    productName: 'Mirror (3-wheeler and jinniu COMMON)',
    productDetails: 'Mirror (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '75',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110110001',
    itemCategory: 'Vehicle Part',
    productName: 'Front bumper footrest (jinniu COMMON)',
    productDetails: 'Front bumper footrest (jinniu COMMON)',
    quantity: 192,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '76',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100160174',
    itemCategory: 'Vehicle Part',
    productName: 'Headlight (jinniu COMMON)',
    productDetails: 'Headlight (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '77',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110190016',
    itemCategory: 'Vehicle Part',
    productName: 'Left turn signal (3-WHEELER)',
    productDetails: 'Left turn signal (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '78',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100190015',
    itemCategory: 'Vehicle Part',
    productName: 'Left turn signal (jinniu COMMON)',
    productDetails: 'Left turn signal (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '79',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-100200065',
    itemCategory: 'Vehicle Part',
    productName: 'Right turn signal (jinniu COMMON)',
    productDetails: 'Right turn signal (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '80',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120300095',
    itemCategory: 'Vehicle Part',
    productName: 'Foot pedal leather (jinniu COMMON)',
    productDetails: 'Foot pedal leather (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '81',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120650095',
    itemCategory: 'Vehicle Part',
    productName: 'For jinlun staff (3-wheeler and jinniu COMMON)',
    productDetails: 'For jinlun staff (3-wheeler and jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '82',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110070049',
    itemCategory: 'Vehicle Part',
    productName: 'Front number plate bracket (jinniu COMMON)',
    productDetails: 'Front number plate bracket (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '83',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120190075',
    itemCategory: 'Vehicle Part',
    productName: 'Pedal latch (jinniu COMMON)',
    productDetails: 'Pedal latch (jinniu COMMON)',
    quantity: 192,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '84',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110190075',
    itemCategory: 'Vehicle Part',
    productName: 'Seat cushion (3-WHEELER)',
    productDetails: 'Seat cushion (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '85',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-120090023',
    itemCategory: 'Vehicle Part',
    productName: 'Backrest (3-WHEELER)',
    productDetails: 'Backrest (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '86',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110070015',
    itemCategory: 'Vehicle Part',
    productName: 'Handlebar cover bracket (3-wheeler and jinniu COMMON)',
    productDetails: 'Handlebar cover bracket (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '87',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110070048',
    itemCategory: 'Vehicle Part',
    productName: 'Display bracket (3-wheeler and jinniu COMMON)',
    productDetails: 'Display bracket (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '88',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110070063',
    itemCategory: 'Vehicle Part',
    productName: 'Tail light bracket (3-WHEELER)',
    productDetails: 'Tail light bracket (3-WHEELER)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '89',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110070064',
    itemCategory: 'Vehicle Part',
    productName: 'Headlight bracket (3-WHEELER)',
    productDetails: 'Headlight bracket (3-WHEELER)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '90',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-190290276',
    itemCategory: 'Vehicle Part',
    productName: 'Seat cushion (jinniu COMMON)',
    productDetails: 'Seat cushion (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '91',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-190010004',
    itemCategory: 'Vehicle Part',
    productName: 'Cable ties (3-wheeler and jinniu COMMON)',
    productDetails: 'Cable ties (3-wheeler and jinniu COMMON)',
    quantity: 100,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '92',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-120280012',
    itemCategory: 'Vehicle Part',
    productName: 'Rear seat backrest (jinniu COMMON)',
    productDetails: 'Rear seat backrest (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '93',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'JN-110070553',
    itemCategory: 'Vehicle Part',
    productName: 'Seat cushion (jinniu COMMON)',
    productDetails: 'Seat cushion (jinniu COMMON)',
    quantity: 96,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
  {
    id: '94',
    purchaseInvoiceNumber: 'CK028',
    vendorName: 'jio ng',
    purchaseDate: new Date('2025-11-14'),
    itemStdCode: 'BW-110280009',
    itemCategory: 'Vehicle Part',
    productName: 'Backrest (3-WHEELER)',
    productDetails: 'Backrest (3-WHEELER)',
    quantity: 4,
    storageLocation: 'Gobi',
    unitPrice: 0,
    purchasePrice: 0,
    itemStatus: 'In Stock',
  },
];
