import type { InventoryItem } from './types';

export const initialInventory: InventoryItem[] = [
  {
    id: '1',
    purchaseInvoiceNumber: 'INV-2023-001',
    vendorName: 'Global Auto Parts',
    date: new Date('2023-10-15'),
    itemStdCode: 'AP-1023',
    itemCategory: 'Vehicle Part',
    productName: 'Brake Pad Set',
    productDetails: 'Front brake pads for Toyota Camry 2022',
    quantity: 50,
    storageLocation: 'Aisle 3, Shelf 2',
    unitPrice: 45.99,
    itemStatus: 'In Stock',
  },
  {
    id: '2',
    purchaseInvoiceNumber: 'INV-2023-002',
    vendorName: 'Machinery World',
    date: new Date('2023-11-01'),
    itemStdCode: 'MW-5500',
    itemCategory: 'Machinery',
    productName: 'Hydraulic Press',
    productDetails: '10-ton hydraulic press for workshop use',
    quantity: 1,
    storageLocation: 'Workshop Area',
    unitPrice: 1200.0,
    itemStatus: 'In Stock',
  },
  {
    id: '3',
    purchaseInvoiceNumber: 'INV-2023-001',
    vendorName: 'Global Auto Parts',
    date: new Date('2023-10-15'),
    itemStdCode: 'AC-8871',
    itemCategory: 'Accessories',
    productName: 'Phone Mount',
    productDetails: 'Universal car phone mount',
    quantity: 150,
    storageLocation: 'Aisle 1, Shelf 1',
    unitPrice: 12.5,
    itemStatus: 'In Stock',
    salesData: [
      { date: '2023-12-01', quantitySold: 20 },
      { date: '2024-01-10', quantitySold: 35 },
    ],
  },
  {
    id: '4',
    purchaseInvoiceNumber: 'INV-2023-003',
    vendorName: 'Solar Direct',
    date: new Date('2023-11-20'),
    itemStdCode: 'SP-300W',
    itemCategory: 'Solar Material',
    productName: '300W Solar Panel',
    productDetails: 'Monocrystalline 300W solar panel',
    quantity: 20,
    storageLocation: 'Warehouse B, Rack 5',
    unitPrice: 150.0,
    itemStatus: 'In Stock',
  },
  {
    id: '5',
    purchaseInvoiceNumber: 'INV-2023-004',
    vendorName: 'Tool Supply Co.',
    date: new Date('2023-12-05'),
    itemStdCode: 'TS-WRSET',
    itemCategory: 'Tools',
    productName: 'Wrench Set',
    productDetails: '24-piece metric and imperial wrench set',
    quantity: 5,
    storageLocation: 'Tool Cabinet 1',
    unitPrice: 75.0,
    itemStatus: 'Own use',
  },
  {
    id: '6',
    purchaseInvoiceNumber: 'INV-2023-001',
    vendorName: 'Global Auto Parts',
    date: new Date('2023-10-15'),
    itemStdCode: 'AP-4501',
    itemCategory: 'Vehicle Part',
    productName: 'Alternator',
    productDetails: 'Alternator for Honda Civic 2020',
    quantity: 10,
    storageLocation: 'Aisle 5, Shelf 4',
    unitPrice: 180.0,
    itemStatus: 'In Stock',
    salesData: [{ date: '2024-02-15', quantitySold: 5 }],
  },
  {
    id: '7',
    purchaseInvoiceNumber: 'INV-2024-005',
    vendorName: 'Battery Universe',
    date: new Date('2024-01-20'),
    itemStdCode: 'BU-LFP100',
    itemCategory: 'Battery Part',
    productName: 'LiFePO4 Battery',
    productDetails: '12V 100Ah Lithium Iron Phosphate Battery',
    quantity: 0,
    storageLocation: 'Battery Rack 1',
    unitPrice: 299.99,
    itemStatus: 'Sold as vehicle',
    salesInvoiceNumber: 'SALE-2024-002',
  },
];
